<a href="https://colab.research.google.com/github/ebasantos/Perceptron-Alg-Python/blob/master/CalculoMatriz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

x = tf.constant([[1,0,2]])
y = tf.constant([[2],[3],[1]])
resultado = tf.matmul(x,y)
print (tf.Session().run(resultado))

x = tf.constant([[1,0],[0,0]])
y = tf.constant([[0,1],[1,0]])
resultado = tf.matmul(x,y)
print (tf.Session().run(resultado))


x = tf.constant([[0,1],[1,0]])
y = tf.constant([[1,0],[0,0]])
resultado = tf.matmul(x,y)
print (tf.Session().run(resultado))

x = tf.constant([[1,2],[3,1],[0,3]])
y = tf.constant([[1,0,1],[2,1,0]])
resultado = tf.matmul(x,y)
print (tf.Session().run(resultado))

[[4]]
[[0 1]
 [0 0]]
[[0 0]
 [1 0]]
[[5 2 1]
 [5 1 3]
 [6 3 0]]
